name: GitHub Actions test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build and deploy
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          npm install
          npm run build
          npm run deploy
